from enum import Enum

class IntentType(str, Enum):
    APPLY_FOR_JOB = "APPLY_FOR_JOB"
    WITHDRAW_APPLICATION = "WITHDRAW_APPLICATION"
    PROPOSE_CONSENT = "PROPOSE_CONSENT"
    REVOKE_CONSENT = "REVOKE_CONSENT"
